[build]
builder = "nixpacks"

[deploy]
startCommand = "cd projects/django-ecommerce && gunicorn ecommerce.wsgi:application --bind 0.0.0.0:$PORT"
healthcheckPath = "/api/health/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[build.nixpacks]
providers = ["python"]
