# Generated by Django 5.2.6 on 2025-09-10 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="event ID"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("payment_intent.succeeded", "Payment Intent Succeeded"),
                            ("payment_intent.payment_failed", "Payment Intent Failed"),
                            ("charge.succeeded", "Charge Succeeded"),
                            ("charge.failed", "Charge Failed"),
                            ("charge.dispute.created", "Dispute Created"),
                            ("invoice.payment_succeeded", "Invoice Payment Succeeded"),
                            ("invoice.payment_failed", "Invoice Payment Failed"),
                        ],
                        max_length=50,
                        verbose_name="event type",
                    ),
                ),
                ("data", models.JSONField(verbose_name="event data")),
                (
                    "processed",
                    models.BooleanField(default=False, verbose_name="processed"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
            ],
            options={
                "verbose_name": "Webhook Event",
                "verbose_name_plural": "Webhook Events",
                "db_table": "webhook_events",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("stripe", "Credit Card (Stripe)"),
                            ("paypal", "PayPal"),
                            ("bank_transfer", "Bank Transfer"),
                            ("cash_on_delivery", "Cash on Delivery"),
                        ],
                        max_length=20,
                        verbose_name="payment method",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                            ("partially_refunded", "Partially Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="amount"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD", max_length=3, verbose_name="currency"
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="transaction ID"
                    ),
                ),
                (
                    "payment_intent_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="payment intent ID"
                    ),
                ),
                (
                    "charge_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="charge ID"
                    ),
                ),
                (
                    "last_four_digits",
                    models.CharField(
                        blank=True, max_length=4, verbose_name="last four digits"
                    ),
                ),
                (
                    "brand",
                    models.CharField(blank=True, max_length=20, verbose_name="brand"),
                ),
                (
                    "expiry_month",
                    models.CharField(
                        blank=True, max_length=2, verbose_name="expiry month"
                    ),
                ),
                (
                    "expiry_year",
                    models.CharField(
                        blank=True, max_length=4, verbose_name="expiry year"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="error message"),
                ),
                (
                    "error_code",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="error code"
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="processed at"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
                "db_table": "payments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("card", "Credit/Debit Card"),
                            ("bank_account", "Bank Account"),
                            ("paypal", "PayPal"),
                        ],
                        max_length=20,
                        verbose_name="payment type",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="default"),
                ),
                (
                    "last_four_digits",
                    models.CharField(
                        blank=True, max_length=4, verbose_name="last four digits"
                    ),
                ),
                (
                    "brand",
                    models.CharField(blank=True, max_length=20, verbose_name="brand"),
                ),
                (
                    "expiry_month",
                    models.CharField(
                        blank=True, max_length=2, verbose_name="expiry month"
                    ),
                ),
                (
                    "expiry_year",
                    models.CharField(
                        blank=True, max_length=4, verbose_name="expiry year"
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="external ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_methods",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Method",
                "verbose_name_plural": "Payment Methods",
                "db_table": "payment_methods",
                "ordering": ["-is_default", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Refund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "refund_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="refund ID"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="amount"
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("customer_request", "Customer Request"),
                            ("defective_product", "Defective Product"),
                            ("wrong_item", "Wrong Item"),
                            ("not_as_described", "Not as Described"),
                            ("duplicate_order", "Duplicate Order"),
                            ("fraudulent", "Fraudulent"),
                            ("other", "Other"),
                        ],
                        default="customer_request",
                        max_length=20,
                        verbose_name="reason",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="processed at"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refunds",
                        to="payments.payment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Refund",
                "verbose_name_plural": "Refunds",
                "db_table": "refunds",
                "ordering": ["-created_at"],
            },
        ),
    ]
