# Generated by Django 5.2.6 on 2025-09-10 20:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="reset_token",
            field=models.CharField(
                blank=True, max_length=32, verbose_name="reset token"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="reset_token_expires",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="reset token expires"
            ),
        ),
    ]
